model:
  base_learning_rate: 5.0e-6  # 4.5e-6
  target: taming.models.model_pmllm_S1.PmllmModel
  params:
    model_name: DT_pocket  # DTA or DTI or DT_pocket
    frozen_proteins_llm: True
    frozen_mols_llm: True
    proteins_llm: pretrain_model/esm2_t30
    mols_llm: pretrain_model/molformer_xl
    p_padding: 1
    m_padding: 2
    p_mask: 32
    m_mask: 3
    training_evaluate: True
    scheduler_type: None
    # ckpt_path:  /storage/v-jinpewang/experiments/vqocr/logs/2024-09-04T23-38-16_vqgan_model_rendered_text_image_100k_server/checkpoints/last.ckpt
    # ignore_keys: ['loss']
    
    mixed_config:
      target: taming.modules.losses.loss_pmllm_S1.mixed_model 
      params:
          model_name: DT_pocket  # DTA or DTI or DT_pocket

          ### tiny original
          # feature transfor
          p_edim: 640 
          m_edim: 768
          p_len: 896
          m_len: 128

          # mixed part
          d_model: 768
          num_heads: 12
          fd_dim: 3072
          num_layers: 12
          dp_out: 0.1

          # Q-former part
          nums_query: 64
          Q_layers: 2

    lossconfig:
      target: taming.modules.losses.loss_pmllm_S1.CELoss 
      params:
        # different loss weights
        p_weight: 1.0
        m_weight: 1.0
        t_weight: 1.0

        # pm_decoder param init 
        d_model: 768
        num_heads: 12
        fd_dim: 3072
        # p GRU decoder 
        # hidden_dim: 512
        len_per: 512

        pocket_len: 64
        pocket_class: 925
        m_len: 128
        m_class: 2362 





# # 正式
# data:
#   target: main.DataModuleFromConfig
#   params:
#     batch_size: 8
#     num_workers: 16
#     train:
#       target: taming.data.PM_Data.DataTrain
#       params:
#         training_list_file: data/DTA_pocket/train_index161_all.json
#     validation:
#       target: taming.data.PM_Data.DataVal
#       params:
#         val_list_file: data/DTA_pocket/val_index161.json


# test
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    train:
      target: taming.data.PM_Data.DataTrain
      params:
        training_list_file: data/DTA_pocket/train_index157_1k.json
    validation:
      target: taming.data.PM_Data.DataVal
      params:
        val_list_file: data/DTA_pocket/val_index157.json



